export default {
  SET_BEER_SUCCESS: 'SET_BEER_SUCCESS',
  SET_BEER_FAIL: 'SET_BEER_FAIL',
  SET_BEER_LOADING: 'SET_BEER_LOADING',

  SET_DRINKER_SUCCESS: 'SET_DRINKER_SUCCESS',
  SET_DRINKER_FAIL: 'SET_DRINKER_FAIL',
  SET_DRINKER_LOADING: 'SET_DRINKER_LOADING',
};
